main/urls.py
from django.urls import path, include
from main import views


app_name = "home"

publications_patterns = [
    path("abstract/", views.tab_publication_abstract, name="abstract"),
    path("proceedings/", views.tab_publication_proceedings, name="proceedings"),
    path("papers/", views.tab_publication_papers, name="papers")
]

tab_patterns = [
    path("users/", views.tab_users, name="users"),
    path("publications/", views.tab_publication_abstract, name="publication"),
    path("publications/", include(publications_patterns)),
    path("conference/", views.tab_conference, name="conference"),
    path("results/", views.tab_results, name='results'),
]

urlpatterns = [
    path("", views.home, name="home"),
    path("", include(tab_patterns)),
]

mw_catalogue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("catalogue/", include("catalogue.urls")),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.
class Team(models.Model):
    name = models.CharField(max_length=30)
    part = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Publication(models.Model):
    authors = models.TextField()
    title   = models.TextField()
    journal = models.TextField()
    doi = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class Proceedings(models.Model):
    authors = models.TextField()
    title = models.TextField()
    journal = models.TextField()
    year = models.IntegerField()
    parameters = models.CharField(max_length=20, null=True, blank=True)
    doi = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return f"{self.journal} // {self.title}"
    
    class Meta:
        verbose_name = 'Proceeding'
        verbose_name_plural = 'Proceedings'
    

class Conference(models.Model):
    name_conf = models.TextField()
    date  = models.CharField(max_length=25)
    place = models.TextField()
    website = models.URLField(null=True, blank=True)
    url_abstract = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name_conf


class Presentation(models.Model):
    class Type(models.TextChoices):
        TALK = 'talk', 'Устный доклад'
        POSTER = 'poster', 'Постер'

    type = models.CharField(max_length=6, choices=Type.choices)
    name = models.TextField()
    first_author = models.CharField(max_length=30)
    authors = models.TextField()
    conf = models.ForeignKey(Conference, on_delete=models.CASCADE, null=True)
    page = models.IntegerField(null=True)
    pdf = models.FileField(null=True, blank=True, upload_to='pdfs/')
    
    class  Meta:
        ordering = ['-type', 'first_author']

    def __str__(self):
        return f"{self.conf} // {self.first_author} // {self.name}"

main/views.py
from typing import Any
from django.shortcuts import render
from main.models import *
from django.views.generic.detail import DetailView


class ConferenceDetailView(DetailView):
    model = Presentation
    context_object_name = 'presentation_list'
    template_name = 'main/tabs/conference.html'

    def get_context_data(self, request, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['presentation_list'] = Presentation.objects.filter(conf_id=self.kwargs['pk'])

        return render(request, "main/tabs/conference.html", context)


def home(request):
    return render(request, "main/main/home.html", {})


def tab_users(request):
    team = Team.objects.all()
    context = {
        "team": team,
        "active-nav-item": 'users',
    }
    return render(request, "main/tabs/users.html", context)


def tab_publications(request):
    return render(request, "main/tabs/publications.html", {})


def tab_conference(request):
    conferences = Conference.objects.all()
    talks = Presentation.objects.filter(type='talk')
    posters = Presentation.objects.filter(type='poster')
    
    context = {
        "conferences": conferences,
        "talks": talks,
        "posters": posters,
    }
    return render(request, "main/tabs/conference.html", context)


def tab_results(request):
    return render(request, "main/tabs/results.html", {})


def tab_publication_abstract(request):
    conferences = Conference.objects.all()
    presentation = Presentation.objects.order_by('first_author', 'name')
    context = {
        "conferences": conferences,
        "presentation": presentation
    }
    return render(request, "main/publications/abstract.html", context)


def tab_publication_proceedings(request):
    proceeding = Proceedings.objects.all()
    context = {'proceedings': proceeding}
    return render(request, "main/publications/proceedings.html", context)


def tab_publication_papers(request):
    return render(request, "main/publications/papers.html", {})

templates/main/publications/abstract.html
{% extends "base_main.html" %}


{% block tab_data %}

<div class='mt-3'>
    <ul class="nav justify-content-center">
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'abstract' %}disabled{% endif %} "
             href="{% url 'home:abstract' %}">Тезисы </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'proceedings' %}disabled{% endif %}"
             href="{% url 'home:proceedings' %}">Труды конференций</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.url_name == 'papers' %}disabled{% endif %}"
             href="{% url 'home:papers' %}">Статьи</a>
        </li>
      </ul>
</div> 

{% block tab_publication %}

{% for conf in conferences %}
    <div class="mt-4">
        <div>
            <h4> <b class='fw-bold'>{{ conf.name_conf }} </b> <a href="{{ conf.url_abstract }}" target="_blank"> <em> [ссылка] </em> </a>  </h4>
            <h5 class="text-muted"> {{ conf.date}}, {{ conf.place }} </h5>
        </div>

    <div class='row g-3 mx-5'>
        <ol>
            {% for press in presentation %}
              {% if press.conf_id == conf.id %}
                <li>
                    {{press.first_author}}, {{press.authors}} //
                    {% if press.page != 0 %}
                      <b class="fw-bold"> {{ press.name }} </b>// C.{{press.page}}.
                    {% else %}
                      <b class="fw-bold"> {{ press.name }}. </b>
                    {% endif %}
                </li>
              {% endif %}
            {% endfor %}
        </ol>
    </div>

{% endfor %}


{% endblock tab_publication %}

{% endblock tab_data %}

templates/main/publications/papers.html
{% extends "base_main.html" %}


{% block tab_data %}

<div class='mt-3'>
  <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'abstract' %}disabled{% endif %} "
           href="{% url 'home:abstract' %}">Тезисы </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'proceedings' %}disabled{% endif %}"
           href="{% url 'home:proceedings' %}">Труды конференций</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'papers' %}disabled{% endif %}"
           href="{% url 'home:papers' %}">Статьи</a>
      </li>
    </ul>
</div> 

{% block tab_publication %}

<h2> Статьи </h2>

{% endblock tab_publication %}

{% endblock tab_data %}

templates/main/publications/proceedings.html
{% extends "base_main.html" %}


{% block tab_data %}

<div class='mt-3'>
  <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'publications' %}disabled{% endif %} "
           href="{% url 'home:abstract' %}">Тезисы </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'proceedings' %}disabled{% endif %}"
           href="{% url 'home:proceedings' %}">Труды конференций</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'papers' %}disabled{% endif %}"
           href="{% url 'home:papers' %}">Статьи</a>
      </li>
    </ul>
</div>  

{% block tab_publication %}

<div class="mt-4">
  <ol>
  {% for publication in proceedings%}
    <li class="mb-2"> 
      {{publication.authors}}.
      <b>{{publication.title}} </b>//
      {{publication.journal}}. {{publication.year}}. {{publication.parameters}}.
      
      {%if publication.doi != NULL %}
        <a href="https://{{ publication.doi }}" target="_blank"> {{ publication.doi }} </a>
      {%endif%}
    </li>
  {% endfor %}
  </ol>
</div>

{% endblock tab_publication %}

{% endblock tab_data %}