catalogue/urls.py
# catalogue/urls.py

from django.urls import path
from catalogue import views

app_name = "catalogue"

urlpatterns = [
    path("", views.month_flare_list, name='month_flare_list'),
    path('<int:year>/<int:month>/<int:day>/', views.flare_list, name='flare_list'),
]

main/urls.py
from django.urls import path, include
from main import views


app_name = "home"

publications_patterns = [
    path("abstract/", views.tab_publication_abstract, name="abstract"),
    path("proceedings/", views.tab_publication_proceedings, name="proceedings"),
    path("papers/", views.tab_publication_papers, name="papers")
]

tab_patterns = [
    path("users/", views.tab_users, name="users"),
    path("publications/", views.tab_publication_abstract, name="publication"),
    path("publications/", include(publications_patterns)),
    path("conference/", views.tab_conference, name="conference"),
    path("results/", views.tab_results, name='results'),
]

urlpatterns = [
    path("", views.home, name="home"),
    path("", include(tab_patterns)),
]

mw_catalogue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("catalogue/", include("catalogue.urls")),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!-- templates/base.html -->
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}MW catalogue{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
    >
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    {% block styles %}
    
    {% endblock styles %}    
</head>
<body class="container">
<header>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-body">
      <div class="container-fluid">
        <button
          data-mdb-collapse-init
          class="navbar-toggler"
          type="button"
          data-mdb-target="#navbarExample01"
          aria-controls="navbarExample01"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarExample01">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item active">
              <a class="nav-link" aria-current="page" href="{% url 'home:home' %}">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'catalogue:month_flare_list'%}">Каталог</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Контакты</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Navbar -->
  </header>

{% block page_content %}

{% endblock page_content %}


<!-- Footer -->
<br>
<br>
<br>
  <footer class="text-center text-white fixed-bottom" style="background-color: #0a4275;">
    <div class="text-center p-3">
      © 2024 Copyright:
      <a class="text-white" href="https://ru.iszf.irk.ru/">ИСЗФ СО РАН</a>
    </div> 
  </footer><!-- Footer -->


</body>
</html>

templates/base_main.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock styles %}


{% block page_content %}
    <!-- Jumbotron -->
    <div class="p-3 text-center bg-body-tertiary">
      <h1 class="mb-3">
        Спектрально-временная морфология излучения солнечных вспышек в микроволновом диапазоне
      </h1>
      <h4 class="mb-3">
        РНФ Проект № 24-22-00315
      </h4>
    </div>

    <!-- Tabs for conference and papers-->
    <ul class="nav nav-tabs mt-3">
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %} "  href="{% url 'home:home' %}">О проекте</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'users' %} active{% endif %}" href="{% url 'home:users' %}">Участники</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'publication' %}active{% endif %}" href="{% url 'home:publication' %}">Публикации</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link {% if request.resolver_match.url_name == 'conference' %}active{% endif %}" href="{% url 'home:conference' %}">Конференции</a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.url_name == 'results' %}active{% endif %}" href="{% url 'home:results' %}">Результаты</a>
      </li>
    </ul>



    {% block tab_data %}


    {% endblock tab_data %}

{% endblock page_content %}